[databases]
# Note: 'account_db' here matches the service name in docker-compose
account_db = host=account_db port=5432 dbname=account_db

[pgbouncer]
listen_port = 6432
listen_addr = *
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
admin_users = finance

# Keep it simple: No SSL for now
client_tls_sslmode = disable
server_tls_sslmode = disable